config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'home#index'
  get 'my_proposals', to: 'proposals#my_proposals'

  root to: 'home#index'
  resources :properties, only:[:show, :new, :create, :index, :edit, :update] do
    resources :proposals, only: [:new, :create]
    resources :price_ranges, only: [:new, :create, :index]
    get 'filtered', on: :collection
    resources :reviews, only: [:new, :create, :show]
  end

  resources :proposals, only:[:index, :show] do
    post 'accept', to: 'proposals#accept_proposal'
    get 'print', to: 'proposals#print_cupom'
  end

  resources :price_ranges, only: [:show, :edit, :update]

  resources :property_types, only: [:show, :new, :create]

  resources :rents, only: [:show]
  get 'my_rents', to: 'rents#my_rents'
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :owner, class_name: 'User'
  has_many :proposals
  has_many :price_ranges
  has_many :property_purposes
  has_many :purposes , through: :property_purposes
  belongs_to :property_type
  has_many :property_reviews
  has_attached_file :photo, styles: { medium: "400x400>", thumb: "100x100>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  def is_available?( start_date, end_date )
    proposals.find_by_sql([' select * from proposals where accepted = :accept and (start_date >= :start_param) and (:end_param >= start_date) or (end_date >= :start_param) and (start_date < :end_param) ', { accept: true, start_param: start_date, end_param: end_date}]).empty?
  end

  def has_review_from?(user)
    property_reviews.where(user: user).any?
  end

  def purpose_list
    purposes = []
    self.purposes.each do |purpose|
      purposes << purpose.name
    end
    purposes.join(', ')
  end
end

app/models/property_type.rb
class PropertyType < ApplicationRecord
  validates :name, presence: { message: 'Você deve preencher o nome do tipo de imóvel' }
  has_many :properties
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_collection, only: [:new, :create, :edit, :update]

  def index
    @properties = Property.all
  end

  def new
    @property = Property.new
    @purposes = Purpose.all
  end

  def create
    @property = Property.new(property_params)
    @property.owner = current_user
    if @property.save
      redirect_to @property
    else
      flash[:error] = 'Este imovel nao pode ser cadastrado sem um proprietario'
      @property = Property.new
      @purposes = Purpose.all
      render :new
    end
  end

  def filtered
    @filter = params[:filter]
    @properties = []
    unless @filter.strip.empty?
      @properties =  Property.all.where('city = ?', @filter)
    end
  end

  def show
    @property = Property.find(params[:id])
    price_range = @property.price_ranges.where('(? between start_date and end_date)', Date.today).first
    unless price_range.nil?
      @property.daily_rate = price_range.daily_rate
    end
  end

  def edit
    @property = Property.find(params[:id])
    @purposes = Purpose.all
  end

  def update
    @property = Property.find(params[:id])
    @property.update(property_params)
    if @property.valid?
      redirect_to @property
    else
      @purposes = Purpose.all
      render :edit
    end
  end

  private

  def set_collection
    @property_types = PropertyType.all
  end

  def property_params
    params.require(:property).permit(:title, :city, :state, :description, :maximum_guests, :daily_rate,
                  :property_type_id, :maximum_rent, :minimun_rent, :rules, :owner, :photo, purpose_ids:[])
  end

end

app/views/properties/_form.html.erb
  <%= form_for  @property do |f| %>

    <div class="form-group">
      <%= f.label :title, 'Titulo' %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :city, 'Cidade' %>
      <%= f.text_field :city, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :state, 'Estado' %>
      <%= f.text_field :state, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :property_type_id, 'Tipo do imovel' %>
      <%= f.collection_select(:property_type_id, @property_types, :id, :name, class: 'form-control')%>
    </div>

    <div class="form-group">
      <%= f.label :daily_rate, 'Preco' %>
      <%= f.text_field :daily_rate, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :maximum_guests, 'Capacidade' %>
      <%= f.text_field :maximum_guests, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :minimun_rent, 'Minimo de dias para hospedagem' %>
      <%= f.text_field :minimun_rent, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :maximum_rent, 'Maximo de dias para hospedagem' %>
      <%= f.text_field :maximum_rent, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.collection_check_boxes(:purpose_ids, @purposes, :id, :name)%>
    </div>

    <div class="form-group">
      <%= f.label :rules, 'Regras' %>
      <%= f.text_field :rules, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :description, 'Descricao' %>
      <%= f.text_area :description, class: 'form-control', style: 'resize: vertical;' %>
    </div>

    <div class="form-group">
      <%= f.label :photo, 'Foto do imóvel' %>
      <%= f.file_field :photo, accept: 'image/png,image/gif,image/jpeg' %>
    </div>

    <%= f.submit 'Enviar', class: "btn btn-default" %>

  <% end %>

app/views/properties/edit.html.erb
<div class='row'>
  <h1>Editar Imovel</h1>
  <div class='col-md-6'>
    <%= render 'form' %>
  </div>
</div>

app/views/properties/filtered.html.erb
<section>
  <h1>Imoveis filtrados por: <%= @filter %></h1>
  <% if @properties.empty? %>
    <h2>Nenhum imovel encontrado nessa cidade.</h2>
  <% else %>
    <% @properties.each do |property| %>
      <div class="col-md-4">
        <h3><%=property.title%></h3>
        <ul>
          <li>Cidade: <%= property.city%> </li>
          <li>Estado: <%= property.state%></li>
          <li>Tipo de residência: <%= property.property_type.name %></li>
          <li>Quantidade máxima de hóspedes: <%= property.maximum_guests %></li>
          <li>Valor da diária: <%= number_to_currency(property.daily_rate) %></li>
        </ul>
      </div>
    <%end%>
  <%end%>
</section>

app/views/properties/filtered_properties.html.erb
<h2>Imoveis filtrados por:<%= @filter %> </h2>
<% if @properties.empty? %>
  <h2>Nenhum imovel encontrado nessa cidade.</h2>
<% else %>
<% @properties.each do |property| %>
  <h3><%=property.title%></h3>
  <ul>
    <li><%= property.city%> </li>
    <li><%= property.state%></li>
    <li><%= property.property_type%></li>
    <li><%= property.maximum_guests%></li>
    <li><%= property.daily_rate%></li>
  </ul>
  <%end%>
<%end%>

app/views/properties/index.html.erb
<table class="table table-striped">
  <tr>
    <th>Nome da Propriedade</th>
    <th></th>
  </tr>
  <% @properties.each do |property| %>
      <tr>
        <td><%= property.title %></td>
        <td><%= link_to 'Editar preços', property_price_ranges_path(property), class: 'btn btn-primary'%>
      </tr>
    <% end %>
</table>

app/views/properties/new.html.erb
<div class='row'>
  <h1>Cadastrar Imovel</h1>
  <div class='col-md-6'>
    <%= render 'form' %>
  </div>
</div>

app/views/properties/show.html.erb
<h1><%= @property.title %></h1>
<h3>Fotos do imóvel</h3>

<% if @property.photo.exists? %>
  <%= image_tag @property.photo.url(:medium) %>
<% else %>
  <%= image_tag "missing.jpg", size: '200x200' %>
<%end %>
<br>
<br>
<ul>
  <li>Tipo da Propriedade: <%= @property.property_type.name %></li>
  <li>Finalidade da locação: <%= @property.purpose_list %></li>
  <li>Cidade: <%= @property.city %></li>
  <li>Estado: <%= @property.state %></li>
  <li>Regras para hospedagem: <%= @property.rules %></li>
  <li>Dono: <%= @property.owner.name %></li>
  <li>Valor da diária: <%= number_to_currency(@property.daily_rate) %></li>
  <li>Quantidade máxima de hospedes: <%= @property.maximum_guests %></li>
  <li>Número mínimo de dias: <%= @property.minimun_rent %></li>
  <li>Número máximo de dias: <%= @property.maximum_rent %></li>
</ul>
<label>Descrição:</label>
<p><%= @property.description %></p>


<%= link_to 'Cadastrar valor por periodo', new_property_price_range_path(@property), class: "btn btn-primary" %>
<%= link_to 'Enviar Proposta', new_property_proposal_path(@property), class: "btn btn-primary" %>
<%= link_to 'Editar', edit_property_path(@property), class: "btn btn-primary" %>