config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'home#index'
  get 'my_proposals', to: 'proposals#my_proposals'

  root to: 'home#index'
  resources :properties, only:[:show, :new, :create, :index, :edit, :update] do
    resources :proposals, only: [:new, :create]
    resources :price_ranges, only: [:new, :create, :index]
    get 'filtered', on: :collection
    resources :reviews, only: [:new, :create, :show]
  end

  resources :proposals, only:[:index, :show] do
    post 'accept', to: 'proposals#accept_proposal'
    get 'print', to: 'proposals#print_cupom'
  end

  resources :price_ranges, only: [:show, :edit, :update]

  resources :property_types, only: [:show, :new, :create]

  resources :rents, only: [:show]
  get 'my_rents', to: 'rents#my_rents'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @properties = Property.all
  end


end

app/views/home/index.html.erb
<section>
  <h1> Aluguel de imoveis </h1>

  <% if user_signed_in? %>
    <%= link_to 'Cadastrar tipo de imovel', new_property_type_path, class: 'btn btn-primary' %>
    <%= link_to 'Cadastrar Imovel', new_property_path, class: "btn btn-primary" %>
    <%= link_to 'Meus imoveis', properties_path, class: "btn btn-primary"%>
    <%= link_to 'Ver propostas', proposals_path, class: "btn btn-primary" %>
  <% end %>

  <br/>

  <% @properties.each do |property| %>
  <div class="col-md-4">
      <h3><%= link_to property.title, property %></h3>
      <ul>
        <li>Cidade: <%= property.city %></li>
        <li>Estado: <%= property.state %></li>
        <li>Finalidade da locação: <%= property.purpose_list %>
        </li>
        <li>Valor da diaria: <%= number_to_currency(property.daily_rate) %></li>
      </ul>
  </div>
  <% end %>
</section>