config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'home#index'
  get 'my_proposals', to: 'proposals#my_proposals'

  root to: 'home#index'
  resources :properties, only:[:show, :new, :create, :index, :edit, :update] do
    resources :proposals, only: [:new, :create]
    resources :price_ranges, only: [:new, :create, :index]
    get 'filtered', on: :collection
    resources :reviews, only: [:new, :create, :show]
  end

  resources :proposals, only:[:index, :show] do
    post 'accept', to: 'proposals#accept_proposal'
    get 'print', to: 'proposals#print_cupom'
  end

  resources :price_ranges, only: [:show, :edit, :update]

  resources :property_types, only: [:show, :new, :create]

  resources :rents, only: [:show]
  get 'my_rents', to: 'rents#my_rents'
end

app/models/proposal.rb
class Proposal < ApplicationRecord
  validates :start_date, :end_date, :total_guests, :name, :email, :cpf,
            :phone, :observation, presence: { message: 'Houve um erro ao tentar enviar a proposta' }
  belongs_to :property
  belongs_to :user
  has_one :rent
  
  after_validation :calculate_total_amount

  private

  def check_start_date?
    unless start_date.nil?
      if start_date <= Date.today
        errors.add(:base, 'Data inicial deve ser maior do que a data de hoje')
        return false
      end
      return true
    end
    false
  end

  def check_end_date?
    unless end_date.nil?
      if start_date > end_date
        errors.add(:base, 'Data final deve ser maior do que a data inicial')
        return false
      end
      return true
    end
    false
  end

  def check_minimum_rent?(days)
    if days < property.minimun_rent
      errors.add(:base, "Quantidade de dias para hospedagem precisa ser maior que #{property.minimun_rent}")
      return false
    end
    true
  end

  def check_maximum_rent?(days)
    if days > property.maximum_rent
      errors.add(:base, "Quantidade de dias para hospedagem precisa ser menor que #{property.maximum_rent}")
      return false
    end
    true
  end

  def calculate_total_amount
    if check_start_date? and check_end_date?
      days = (end_date - start_date).to_i
      if check_minimum_rent?(days) and check_maximum_rent?(days)
        self.total_amount = (property.daily_rate * days).to_f
      end
    end
  end


end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController

  def index
    @proposals = Proposal.all.where(accepted: false)
  end

  def show
    @proposal = Proposal.find(params[:id])
  end

  def new
    find_property
    @proposal = @property.proposals.new
  end

  def create
    find_property

    price_range = @property.price_ranges.where('(? between start_date and end_date)', Date.today).first
    unless price_range.nil?
      @property.daily_rate = price_range.daily_rate
    end

    @proposal = @property.proposals.new(proposal_params)
    @proposal.user = current_user
    if @property.is_available?( @proposal.start_date, @proposal.end_date )
      if @proposal.save
        redirect_to @proposal
      else
        flash[:error] = 'Houve um erro ao tentar enviar a proposta'
        render :new
      end
    else
      flash[:error] = 'casa indisponivel'
      render :new
    end
  end

  def accept_proposal
    @proposal = Proposal.find(params[:proposal_id])
    @proposal.accepted = true

    @proposal.save
    flash[:notice] = 'Proposta aceita..'

    rent = Rent.create( proposal: @proposal )
    redirect_to rent_url(rent)
  end

  def my_proposals
    @proposals = Proposal.where(user: current_user)
  end

  def print_cupom
    @proposal = Proposal.find(params[:proposal_id])
  end

  private

  def find_property
    @property = Property.find(params[:property_id])
  end

  def proposal_params
    parameters = params.require(:proposal).permit(:start_date, :end_date, :total_guests, :name,
                 :email, :cpf, :phone, :observation)
  end

 end

app/views/proposals/index.html.erb
<h1>Minhas propostas</h1>

<section>
  <% if @proposals.empty? %>
    <p>Nenhuma proposta ainda</p>
  <% else %>
    <% @proposals.each do |proposal| %>
    <div class="col-md-4">
      <h3><%= link_to proposal.property.title, proposal_path(proposal) %></h3>
      <ul>
        <li>Data Inicial: <%= I18n.l(proposal.start_date)%></li>
        <li>Data Final: <%= I18n.l(proposal.end_date) %></li>
        <li>Valor total da hospedagem: <%= number_to_currency(proposal.total_amount) %> </li>
      </ul>
    </div>
    <% end %>
  <% end %>
</section>

app/views/proposals/my_proposals.html.erb
<% if @proposals.empty? %>
<p> Voce nao possui propostas cadastradas</p>
<% else %>
  <% @proposals.each do |proposal| %>
    <h1> <%= proposal.property.description %></h1>
    <li><%= proposal.start_date %></li>
    <li><%= proposal.end_date %></li>
    <li><%= proposal.total_amount %></li>


    <%= link_to 'Imprimir Comprovante', proposal_print_path(proposal) %>
  <% end %>
<%end %>

app/views/proposals/new.html.erb
<% unless @proposal.errors.full_messages.empty? %>
  <div class="alert alert-danger">
    <% @proposal.errors.full_messages.each do |message| %>
      <label><%= message %></label>
    <% end %>
  </div>
<%end%>

<div class='row'>
  <h1>Enviar Proposta</h1>
  <div class='col-md-6'>
    <%= form_for([@property, @proposal]) do |f| %>
      <div class="form-group">
        <%= f.label :start_date, 'Data Inicial' %>
        <%= f.date_field :start_date, min: Date.today, class: 'form-control'%>
      </div>

      <div class="form-group">
        <%= f.label :end_date, 'Data Final' %>
        <%= f.date_field :end_date, min: Date.today, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :total_guests, 'Quantidade de hóspedes' %>
        <%= f.number_field :total_guests, class: 'form-control'%>
      </div>

      <div class="form-group">
        <%= f.label :name, 'Nome' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :cpf, 'CPF' %>
        <%= f.text_field :cpf, size: 11, class: 'form-control'%>
      </div>
      <div class="form-group">
        <%= f.label :phone, 'Telefone' %>
        <%= f.phone_field :phone, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :observation, 'Observações' %>
        <%= f.text_area :observation, class: 'form-control'%>
      </div>
      <%= f.submit 'Enviar', class: "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/proposals/print_cupom.html.erb
<h1> Comprovante de locacao </h1>

<p> Eu, <%= @proposal.property.owner %>, portador do CPF 123.456.789-02 declaro para os devidos fins que alugo o imovel situado
    a <%= @proposal.property.city %> para <%= @proposal.user.name %> portadora do CPF <%= @proposal.cpf %>, entre o periodo de
    <%= @proposal.start_date %> a <%= @proposal.end_date %>, pelo valor total de <%= @proposal.total_amount %>. </p>

<p> Para este periodo, devem ser respeitada as seguintes regras:

  <%= @proposal.property.rules %></p>

app/views/proposals/show.html.erb
<h1>Proposta</h1>
  <ul>
      <li>Data Inicial: <%= I18n.l(@proposal.start_date) %></li>
      <li>Data Final: <%= I18n.l(@proposal.end_date) %></li>
      <li>Valor total: <%= number_to_currency(@proposal.total_amount) %></li>
      <li>Quantidade de hóspede: <%= @proposal.total_guests %></li>
      <li>Nome: <%= @proposal.name %></li>
      <li>CPF: <%= @proposal.cpf %></li>
      <li>Email: <%= @proposal.email %></li>
      <li>Telefone: <%= @proposal.phone %></li>
      <li>Observações: <%= @proposal.observation %></li>
  </ul>



<%= link_to 'Aceitar', proposal_accept_path(@proposal), method: :post, class: 'btn btn-primary' %>