config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'home#index'
  get 'my_proposals', to: 'proposals#my_proposals'

  root to: 'home#index'
  resources :properties, only:[:show, :new, :create, :index, :edit, :update] do
    resources :proposals, only: [:new, :create]
    resources :price_ranges, only: [:new, :create, :index]
    get 'filtered', on: :collection
    resources :reviews, only: [:new, :create, :show]
  end

  resources :proposals, only:[:index, :show] do
    post 'accept', to: 'proposals#accept_proposal'
    get 'print', to: 'proposals#print_cupom'
  end

  resources :price_ranges, only: [:show, :edit, :update]

  resources :property_types, only: [:show, :new, :create]

  resources :rents, only: [:show]
  get 'my_rents', to: 'rents#my_rents'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlugaTemporada</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= favicon_link_tag 'sun.gif' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
        <nav class="navbar navbar-inverse">
          <div class="container">
            <div class="navbar-header">
              <%= image_tag "sun.gif", alt:"Brand", class: 'navbar-brand', style:'width: 60px; height: 60px;' %>
              <%= link_to 'Aluga Verão', root_path, class: "navbar-brand" %>
            </div>
            <div class="navbar-right">
              <label class="navbar-text">Bem vindo ao Aluga Verão</label>
                <%= render 'shared/filter_form' %>
              <% if user_signed_in? %>
                <%= link_to 'Minhas locações', my_rents_path, class: 'btn btn-primary', style: 'margin-top: 7px;' %>
                <%= link_to 'Minhas propostas', my_proposals_path, class: 'btn btn-primary', style: 'margin-top: 7px;' %>
                <%= link_to 'Logout', destroy_user_session_path, method: 'delete', class: 'btn btn-primary', style: 'margin-top: 7px;'  %>
              <% else %>
                <%= link_to 'Login', new_user_session_path, class: 'btn btn-primary', style: 'margin-top: 7px;' %>
                <%= link_to 'Cadastrar', new_user_registration_path, class: 'btn btn-primary', style: 'margin-top: 7px;' %>
              <% end %>
            </div>
          </div>
        </nav>
      </header>

    <main>
      <div class="container">
        <%= render 'shared/notifications' %>
        <%= yield %>
      </div>
    </main>
  </body>
</html>